###

POST http://localhost:3000/duels:create HTTP/1.1
content-type: application/json

{
  "activePlayerId": "player-1",
  "players": [
    {
      "id": "player-1",
      "deck": [
        { "cardId": "brainsucker" }
      ]
    },
    {
      "id": "player-2",
      "deck": [
        { "cardId": "brainsucker" }
      ]
    }
  ]
}

### 
GET http://localhost:3000/duels:active HTTP/1.1
content-type: application/json
